### ISSUE TITLE
OOW15 - Presentation

### ISSUE THREAD

**Issue by DarraghDuffy** [martindsouza/pres-open-source-apex#3]
excellent presentation  - well done. 
I had a few questions but did not get to chat - 
- OXAR is this running ORDS3 ?
- I am currently running a very (very) large application through mod_plsql, any thoughts on node_plsql v's ORDS, I will be migrating from mod_plsql to ORDS or Node.

**Comment by martindsouza** [comment]
@DarraghDuffy Thanks for the feedback.
- OXAR: Yes it's running 3. It's really what ever version you upload to your server. More info on support versions [here](https://github.com/OraOpenSource/OXAR#current-software-versions).
  - I used the latest version of ORDS last week and it worked fine.
- Use ORDS. I'm not sure of node_plsql however ORDS is maintained from Oracle and they have quick release cycle.
  - If you want to use Node.js we have a wrapper around ORDS called [node4ords](https://github.com/OraOpenSource/node4ords), which is use in [OXAR](https://github.com/OraOpenSource/OXAR). I don't recommend this for production use yet however it may be good to try it out. If you'd like to help on the project please let me know.

**Comment by slou68** [comment]
Your presentation was the first one I joined today on the first day of Oracle Open World. :100: I really enjoyed your presentation. It is clear and very informative. Well done!

**Comment by fmignault** [comment]
Great presentation Martin ! :+1: 
I think that more and more people will use apex-diff in their projects.

**Comment by martindsouza** [comment]
@slou68 @fmignault Thanks for your feedback and coming out to the [ODTUG](http://www.odtug.com) meetup on Tuesday night. If you liked this presentation, there will be a lot more at [KScope 16](http://kscope16.com) in Chicago next summer. Hopefully we'll see you there.

**Comment by Jakobmhc** [comment]
Hey Martin
Just wanted to say I also enjoyed your presentaion, being the first for me on oow, I had really high hope/standards for the rest of the sessions but actually only a few where as good which then where disappointing...
I learned quite alot and will be pushing logger and apex-diff at the client.
If I were to use OXAR in a private project, what would you suggest to use as a server? Is it overkill to use AWS when it will be used for <100 users?

**Comment by martindsouza** [comment]
@Jakobmhc Thanks for the feedback and I'm glad that you enjoyed the presentation.

re OXAR. Cloud provider is entirely up to you. I tend to use it on CentOS builds on [Digital Ocean](https://www.digitalocean.com) and also locally in VirtualBox machines. I have tested it in AWS and it works. 

As for overkill on hosting on AWS, it depends on how much management you want to do. I like using Digital Ocean since it's very simple to manage and saves me time managing my own server.
