### ISSUE TITLE
Oxar

### ISSUE THREAD

**Issue by rangerzzoxz** [martindsouza/pres-open-source-apex#4]
I just installed oxar centos7, oracle xe, apex5.0.2, ords3.0.2, and sqlcl fronted by apache https instead of nodejs (so I can do ssl) and it works great.  Thanks so much for putting together such a flexible setup.

**Comment by rangerzzoxz** [comment]
I did watch the presentation (I'm not at oow) and you did a great job explaining the oraopensource project.

**Comment by martindsouza** [comment]
Thanks for the feedback. 

Regarding SSL, we're waiting for LetsEncrypt to be out then we'll integrate native SSL support. There's an [OXAR Ticket](https://github.com/OraOpenSource/OXAR/issues/33) for this.

**Comment by rangerzzoxz** [comment]
Yes, you are correct.  I gave up waiting for them. And we already deploy Database SE, tomcat, ORDS3, and Apache in production (with Apache doing the SSL).  Any thoughts on whether NODE is the right choice for doing the web listener (and perhaps compressing/caching) job?  Versus Apache HTTPD as an example?

I'm happy I was able to build a setup and got it working the first time.  :)
By simply selecting the NODE portion from Y to N and then installing HTTPD myself after everything finished (then setting HTTPD up to "front" tomcat via AJP).

**Comment by martindsouza** [comment]
Node.js / Express is good enough for the web listener however [Node4ORDS](https://github.com/OraOpenSource/node4ords) isn't production ready. Still need some help on that.

Main reason why we included N4O in OXAR was a learning experience for me and to hopefully enhance it to allow for easy integrations of other technologies (ex websockets).
